services:
  - type: web
    name: ai-lung-detector
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --only-binary=all -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 180 --workers 1 --max-requests 100 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true