services:
  - type: web
    name: ai-lung-detector
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    healthCheckPath: /
    autoDeploy: true